[project]
name = "yeat-gpt"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "httpx>=0.28.1",
    "lxml>=6.0.2",
    "polars>=1.36.1",
    "python-dotenv>=1.2.1",
]
